# Generated by Django 5.1.3 on 2024-11-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialità',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnia', models.PositiveSmallIntegerField()),
                ('lega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lega')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sport')),
            ],
        ),
    ]
